obj-m += tiler2_dmm.o
tiler2_dmm-objs = dmm.o

obj-m += tiler2.o
tiler2-objs = tiler-main.o tiler-geom.o tiler-iface.o tiler-reserve.o tmm-pat.o tiler-nv12.o tiler-ioctl.o

obj-m += ion_driver.o
ion_driver-objs += ion.o

obj-m += virtio.o
obj-m += virtio_rpmsg_bus.o
obj-m += virtio_ring.o

obj-m += rpres.o
#obj-m += remoteproc.o

obj-m += rpmsg_resmgr_driver.o
rpmsg_resmgr_driver-objs += rpmsg_resmgr.o omap_hwmod.o

#obj-m += rpmsg_omx_driver.o
#rpmsg_omx_driver-objs += rpmsg_omx.o omap_hwmod.o


