obj-m += tiler2_dmm.o
tiler2_dmm-objs = dmm.o

obj-m += tiler2.o
tiler2-objs = tiler-geom.o tiler-main.o tiler-iface.o tiler-reserve.o tmm-pat.o tiler-nv12.o tiler-ioctl.o

obj-m += ion_driver.o
ion_driver-objs += ion.o ion_heap.o ion_system_heap.o ion_carveout_heap.o omap_ion.o omap_tiler_heap.o

