obj-m += xt_quota2.o
#ATOP  := ~/android/cyanogenmod
#CC    := $(ATOP)/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/arm-eabi-
#KOUT  := $(ATOP)/out/target/product/solana
#PWD   := $(shell pwd)

#default:
#$(MAKE) -j1 -C ~/android/cyanogenmod/kernel/omap4 ARCH=arm PROCFAMILY=OMAP4430 PROJROOT= HOST_PLATFORM=sdc4430 CROSS_COMPILE=$(CC) O=$(KOUT) M=`pwd`

#clean:
#$(MAKE) PREFIX=$(KOUT) ARCH=arm CROSS_COMPILE=~/android/cyanogenmod/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/arm-eabi- PROCFAMILY=OMAP4430 PROJROOT= HOST_PLATFORM=sdc4430 -C $(KDIR) M=$(PWD) clean

